In [11]:
import pandas as pd
data1 = pd.read_csv('CE_Seq_25PDB.csv')
labels = data1['Class'].values
feat_w2v = data1.drop(['PDBid', 'Class', 'Unnamed: 0'], axis=1).values


from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

rf = RandomForestClassifier(n_estimators=360, criterion="gini")
gb = GradientBoostingClassifier(n_estimators=360, learning_rate=0.01, max_depth=3)
sv = SVC(kernel='rbf', C=4, probability=True)
eclf = VotingClassifier(estimators=[('rf', rf),('gb', gb),('sv', sv)], voting='soft')

import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

import numpy as np
from sklearn.metrics import accuracy_score
acc_eclf = []

for train, test in kf.split(feat_w2v, labels):
    X_train, X_test = feat_w2v[train], feat_w2v[test]
    Y_train, Y_test = labels[train], labels[test]
    
    eclf.fit(X_train, Y_train)
    pred = eclf.predict(X_test).round()
    print confusion_matrix(pred, Y_test)
    print classification_report(pred, Y_test)
    acc_eclf.append(accuracy_score(pred, Y_test))

print '\nFold Accuracies: ', acc_eclf
print '\nAccuracy Ensemble Classifier: ', np.mean(acc_eclf)

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[32  4  3  9]
 [ 2 31  5 12]
 [ 5  4 19 11]
 [ 6  6  8 13]]
             precision    recall  f1-score   support

          0       0.71      0.67      0.69        48
          1       0.69      0.62      0.65        50
          2       0.54      0.49      0.51        39
          3       0.29      0.39      0.33        33

avg / total       0.58      0.56      0.57       170



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[29  3  2 12]
 [ 6 24  7 11]
 [ 1  5 19  8]
 [ 9 13  7 13]]
             precision    recall  f1-score   support

          0       0.64      0.63      0.64        46
          1       0.53      0.50      0.52        48
          2       0.54      0.58      0.56        33
          3       0.30      0.31      0.30        42

avg / total       0.51      0.50      0.50       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[31  3  4 12]
 [ 3 28  7 12]
 [ 3  8 17  7]
 [ 8  6  7 13]]
             precision    recall  f1-score   support

          0       0.69      0.62      0.65        50
          1       0.62      0.56      0.59        50
          2       0.49      0.49      0.49        35
          3       0.30      0.38      0.33        34

avg / total       0.55      0.53      0.54       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[30  4  2  9]
 [ 2 26 10 13]
 [ 6  6 17  9]
 [ 6  8  6 13]]
             precision    recall  f1-score   support

          0       0.68      0.67      0.67        45
          1       0.59      0.51      0.55        51
          2       0.49      0.45      0.47        38
          3       0.30      0.39      0.34        33

avg / total       0.53      0.51      0.52       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[31  3 11 12]
 [ 2 26  5 12]
 [ 0  4 14  6]
 [11 11  5 14]]
             precision    recall  f1-score   support

          0       0.70      0.54      0.61        57
          1       0.59      0.58      0.58        45
          2       0.40      0.58      0.47        24
          3       0.32      0.34      0.33        41

avg / total       0.54      0.51      0.52       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[19  5  2  6]
 [ 7 24  5 15]
 [ 4  6 22 11]
 [14  9  6 12]]
             precision    recall  f1-score   support

          0       0.43      0.59      0.50        32
          1       0.55      0.47      0.51        51
          2       0.63      0.51      0.56        43
          3       0.27      0.29      0.28        41

avg / total       0.48      0.46      0.46       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[30  8  3 12]
 [ 6 26  7 11]
 [ 3  4 16 10]
 [ 5  6  8 11]]
             precision    recall  f1-score   support

          0       0.68      0.57      0.62        53
          1       0.59      0.52      0.55        50
          2       0.47      0.48      0.48        33
          3       0.25      0.37      0.30        30

avg / total       0.53      0.50      0.51       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[34  3  6 14]
 [ 1 30  7 11]
 [ 5  2 16  7]
 [ 4  9  5 12]]
             precision    recall  f1-score   support

          0       0.77      0.60      0.67        57
          1       0.68      0.61      0.65        49
          2       0.47      0.53      0.50        30
          3       0.27      0.40      0.32        30

avg / total       0.60      0.55      0.57       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[31  3  1 11]
 [ 4 27  9 12]
 [ 7  5 18  9]
 [ 2  9  6 12]]
             precision    recall  f1-score   support

          0       0.70      0.67      0.69        46
          1       0.61      0.52      0.56        52
          2       0.53      0.46      0.49        39
          3       0.27      0.41      0.33        29

avg / total       0.56      0.53      0.54       166

[[28  6  2 10]
 [ 4 24  4 12]
 [ 4  4 19  7]
 [ 8 10  9 15]]
             precision    recall  f1-score   support

          0       0.64      0.61      0.62        46
          1       0.55      0.55      0.55        44
          2       0.56      0.56      0.56        34
          3       0.34      0.36      0.35        42

avg / total       0.52      0.52      0.52       166


Fold Accuracies:  [0.5588235294117647, 0.5029585798816568, 0.5266272189349113, 0.5149700598802395, 0.5089820359281437, 0.46107784431137727, 0.5, 0.5542168674698795, 0.5301204819277109, 0.5180722891566265]

Accuracy Ensemble Classifier:

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [12]:
import pandas as pd
data1 = pd.read_csv('25PDB/CE_Str_25PDB.csv')
labels = data1['Class'].values
feat_w2v = data1.drop(['PDBid', 'Class', 'Unnamed: 0'], axis=1).values


from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

rf = RandomForestClassifier(n_estimators=360, criterion="gini")
gb = GradientBoostingClassifier(n_estimators=360, learning_rate=0.01, max_depth=3)
sv = SVC(kernel='rbf', C=4, probability=True)
eclf = VotingClassifier(estimators=[('rf', rf),('gb', gb),('sv', sv)], voting='soft')

import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

import numpy as np
from sklearn.metrics import accuracy_score
acc_eclf = []

for train, test in kf.split(feat_w2v, labels):
    X_train, X_test = feat_w2v[train], feat_w2v[test]
    Y_train, Y_test = labels[train], labels[test]
    
    eclf.fit(X_train, Y_train)
    pred = eclf.predict(X_test).round()
    print confusion_matrix(pred, Y_test)
    print classification_report(pred, Y_test)
    acc_eclf.append(accuracy_score(pred, Y_test))

print '\nFold Accuracies: ', acc_eclf
print '\nAccuracy Ensemble Classifier: ', np.mean(acc_eclf)

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[42  0  1  1]
 [ 0 34  1  3]
 [ 2  3 23 12]
 [ 1  8 10 29]]
             precision    recall  f1-score   support

          0       0.93      0.95      0.94        44
          1       0.76      0.89      0.82        38
          2       0.66      0.57      0.61        40
          3       0.64      0.60      0.62        48

avg / total       0.75      0.75      0.75       170



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[37  1  1  4]
 [ 0 34  0  0]
 [ 6  0 24 11]
 [ 2 10 10 29]]
             precision    recall  f1-score   support

          0       0.82      0.86      0.84        43
          1       0.76      1.00      0.86        34
          2       0.69      0.59      0.63        41
          3       0.66      0.57      0.61        51

avg / total       0.73      0.73      0.72       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[42  1  4  3]
 [ 0 36  1  6]
 [ 1  0 19  8]
 [ 2  8 11 27]]
             precision    recall  f1-score   support

          0       0.93      0.84      0.88        50
          1       0.80      0.84      0.82        43
          2       0.54      0.68      0.60        28
          3       0.61      0.56      0.59        48

avg / total       0.74      0.73      0.74       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[42  0  3  1]
 [ 1 33  0  3]
 [ 0  3 23 14]
 [ 1  8  9 26]]
             precision    recall  f1-score   support

          0       0.95      0.91      0.93        46
          1       0.75      0.89      0.81        37
          2       0.66      0.57      0.61        40
          3       0.59      0.59      0.59        44

avg / total       0.74      0.74      0.74       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[38  1  4  3]
 [ 0 36  0  5]
 [ 6  0 21  6]
 [ 0  7 10 30]]
             precision    recall  f1-score   support

          0       0.86      0.83      0.84        46
          1       0.82      0.88      0.85        41
          2       0.60      0.64      0.62        33
          3       0.68      0.64      0.66        47

avg / total       0.75      0.75      0.75       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[43  0  3  2]
 [ 0 35  0  7]
 [ 0  1 21  9]
 [ 1  8 11 26]]
             precision    recall  f1-score   support

          0       0.98      0.90      0.93        48
          1       0.80      0.83      0.81        42
          2       0.60      0.68      0.64        31
          3       0.59      0.57      0.58        46

avg / total       0.76      0.75      0.75       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[38  0  1  1]
 [ 0 30  0  5]
 [ 3  5 20 15]
 [ 3  9 13 23]]
             precision    recall  f1-score   support

          0       0.86      0.95      0.90        40
          1       0.68      0.86      0.76        35
          2       0.59      0.47      0.52        43
          3       0.52      0.48      0.50        48

avg / total       0.66      0.67      0.66       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[39  1  2  3]
 [ 0 34  0  3]
 [ 3  1 24 10]
 [ 2  8  8 28]]
             precision    recall  f1-score   support

          0       0.89      0.87      0.88        45
          1       0.77      0.92      0.84        37
          2       0.71      0.63      0.67        38
          3       0.64      0.61      0.62        46

avg / total       0.75      0.75      0.75       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[41  2  4  2]
 [ 0 32  0  7]
 [ 2  1 22 13]
 [ 1  9  8 22]]
             precision    recall  f1-score   support

          0       0.93      0.84      0.88        49
          1       0.73      0.82      0.77        39
          2       0.65      0.58      0.61        38
          3       0.50      0.55      0.52        40

avg / total       0.71      0.70      0.71       166

[[37  0  2  2]
 [ 0 31  1  4]
 [ 5  1 18  8]
 [ 2 12 13 30]]
             precision    recall  f1-score   support

          0       0.84      0.90      0.87        41
          1       0.70      0.86      0.78        36
          2       0.53      0.56      0.55        32
          3       0.68      0.53      0.59        57

avg / total       0.70      0.70      0.69       166


Fold Accuracies:  [0.7529411764705882, 0.7337278106508875, 0.7337278106508875, 0.7425149700598802, 0.7485029940119761, 0.7485029940119761, 0.6686746987951807, 0.7530120481927711, 0.7048192771084337, 0.6987951807228916]

Accuracy Ensemb

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [13]:
#Combined
import pandas as pd
data1 = pd.read_csv('25PDB/CE_Seq_25PDB.csv')
data2 = pd.read_csv('25PDB/CE_Str_25PDB.csv')

features1 = data1.drop(['Unnamed: 0'], axis=1)
features2 = data2.drop(['Unnamed: 0', 'Class'], axis=1)
features12 = features1.merge(features2, on=['PDBid'], how='inner')

labels = features12['Class'].values
feat_w2v = features12.drop(['PDBid', 'Class'], axis=1).values


from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

rf = RandomForestClassifier(n_estimators=360, criterion="gini")
gb = GradientBoostingClassifier(n_estimators=360, learning_rate=0.01, max_depth=3)
sv = SVC(kernel='rbf', C=4, probability=True)
eclf = VotingClassifier(estimators=[('rf', rf),('gb', gb),('sv', sv)], voting='soft')

import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

import numpy as np
from sklearn.metrics import accuracy_score
acc_eclf = []

for train, test in kf.split(feat_w2v, labels):
    X_train, X_test = feat_w2v[train], feat_w2v[test]
    Y_train, Y_test = labels[train], labels[test]
    
    eclf.fit(X_train, Y_train)
    pred = eclf.predict(X_test).round()
    print confusion_matrix(pred, Y_test)
    print classification_report(pred, Y_test)
    acc_eclf.append(accuracy_score(pred, Y_test))

print '\nFold Accuracies: ', acc_eclf
print '\nAccuracy Ensemble Classifier: ', np.mean(acc_eclf)

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[40  0  0  1]
 [ 0 34  1  3]
 [ 4  0 27  9]
 [ 1 11  7 32]]
             precision    recall  f1-score   support

          0       0.89      0.98      0.93        41
          1       0.76      0.89      0.82        38
          2       0.77      0.68      0.72        40
          3       0.71      0.63      0.67        51

avg / total       0.78      0.78      0.78       170



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[36  1  0  4]
 [ 0 36  0  2]
 [ 4  1 26  8]
 [ 5  7  9 30]]
             precision    recall  f1-score   support

          0       0.80      0.88      0.84        41
          1       0.80      0.95      0.87        38
          2       0.74      0.67      0.70        39
          3       0.68      0.59      0.63        51

avg / total       0.75      0.76      0.75       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[41  1  3  3]
 [ 0 36  1  7]
 [ 2  0 21  6]
 [ 2  8 10 28]]
             precision    recall  f1-score   support

          0       0.91      0.85      0.88        48
          1       0.80      0.82      0.81        44
          2       0.60      0.72      0.66        29
          3       0.64      0.58      0.61        48

avg / total       0.75      0.75      0.75       169



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[42  0  1  1]
 [ 1 32  1  5]
 [ 0  2 22  8]
 [ 1 10 11 30]]
             precision    recall  f1-score   support

          0       0.95      0.95      0.95        44
          1       0.73      0.82      0.77        39
          2       0.63      0.69      0.66        32
          3       0.68      0.58      0.62        52

avg / total       0.75      0.75      0.75       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[36  1  4  3]
 [ 0 35  0  6]
 [ 2  0 22  7]
 [ 6  8  9 28]]
             precision    recall  f1-score   support

          0       0.82      0.82      0.82        44
          1       0.80      0.85      0.82        41
          2       0.63      0.71      0.67        31
          3       0.64      0.55      0.59        51

avg / total       0.72      0.72      0.72       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[39  1  1  2]
 [ 0 34  0  9]
 [ 1  3 29  7]
 [ 4  6  5 26]]
             precision    recall  f1-score   support

          0       0.89      0.91      0.90        43
          1       0.77      0.79      0.78        43
          2       0.83      0.72      0.77        40
          3       0.59      0.63      0.61        41

avg / total       0.77      0.77      0.77       167



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[38  2  1  2]
 [ 0 30  0  6]
 [ 1  1 21  8]
 [ 5 11 12 28]]
             precision    recall  f1-score   support

          0       0.86      0.88      0.87        43
          1       0.68      0.83      0.75        36
          2       0.62      0.68      0.65        31
          3       0.64      0.50      0.56        56

avg / total       0.70      0.70      0.70       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[39  1  2  3]
 [ 0 36  0  2]
 [ 3  1 23  8]
 [ 2  6  9 31]]
             precision    recall  f1-score   support

          0       0.89      0.87      0.88        45
          1       0.82      0.95      0.88        38
          2       0.68      0.66      0.67        35
          3       0.70      0.65      0.67        48

avg / total       0.77      0.78      0.77       166



/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[42  2  4  2]
 [ 0 32  0  7]
 [ 1  0 22  9]
 [ 1 10  8 26]]
             precision    recall  f1-score   support

          0       0.95      0.84      0.89        50
          1       0.73      0.82      0.77        39
          2       0.65      0.69      0.67        32
          3       0.59      0.58      0.58        45

avg / total       0.74      0.73      0.74       166

[[40  0  1  3]
 [ 0 32  1  3]
 [ 0  1 19  3]
 [ 4 11 13 35]]
             precision    recall  f1-score   support

          0       0.91      0.91      0.91        44
          1       0.73      0.89      0.80        36
          2       0.56      0.83      0.67        23
          3       0.80      0.56      0.65        63

avg / total       0.78      0.76      0.76       166


Fold Accuracies:  [0.7823529411764706, 0.757396449704142, 0.7455621301775148, 0.7544910179640718, 0.7245508982035929, 0.7664670658682635, 0.7048192771084337, 0.7771084337349398, 0.7349397590361446, 0.7590361445783133]

Accuracy Ensembl

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
